In [2]:
print("hello i am excited to start with ai")

hello i am excited to start with ai


In [3]:
nvidia-smi

NameError: name 'nvidia' is not defined

In [4]:
import torch
print (torch.version)

<module 'torch.version' from 'c:\\Users\\nagah\\anaconda3\\Lib\\site-packages\\torch\\version.py'>


In [5]:
%%time
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.version)
print(torch.version.cuda)


<module 'torch.version' from 'c:\\Users\\nagah\\anaconda3\\Lib\\site-packages\\torch\\version.py'>
13.0
CPU times: total: 1.95 s
Wall time: 6.85 s


In [ ]:
# #scalars
# import torch
# #scalar=torch.tensor(7)
# scalar = torch.tensor(7)
# scalar
# scalar.ndim

import torch
#%%time
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)


UsageError: Line magic function `%%time` not found.


In [3]:
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
#vector
vector=torch.tensor([7,7])
#vector

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix
#MATRIX=torch.tensor([3,5],[5,6])
print(type(torch))
print(torch)
matrix=torch.tensor([3,5])

<class 'module'>
<module 'torch' from 'c:\\Users\\nagah\\anaconda3\\Lib\\site-packages\\torch\\__init__.py'>


In [ ]:
#random tensors

#why random tensors
#beasue the way newural networks learn is that they start with tensors full of random numbers and adjust the numbers to  reporesent the better  data

# start with random number>look at the data>update the random numbers>look at the data>update the random numbers

# https://docs.pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html 
# https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [13]:
%%time
random_tensor=torch.rand(1,2, 3,4)
random_tensor


CPU times: total: 0 ns
Wall time: 180 μs


tensor([[[[0.2349, 0.7445, 0.8263, 0.5263],
          [0.1260, 0.5124, 0.6552, 0.8149],
          [0.2133, 0.7542, 0.5207, 0.0798]],

         [[0.3560, 0.3427, 0.1526, 0.6384],
          [0.6013, 0.5727, 0.4562, 0.7797],
          [0.9838, 0.0140, 0.3614, 0.9115]]]])

In [14]:
random_tensor.ndim

4

In [15]:
random_image_size_tensor= torch.rand(size=(224,223,3))#height,width,color, color channels are Red,Gree,Blue
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 223, 3]), 3)

In [16]:
zero=torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
zero*random_tensor

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

In [18]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

In [20]:
random_tensor.dtype

torch.float32

In [22]:
#torch range
torch.range(0,10)
#torch.arrange(0,10)
torch.arange(0,10)


C:\Users\nagah\AppData\Local\Temp\ipykernel_3668\2582402264.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#https://docs.pytorch.org/docs/stable/generated/torch.arange.html
torch.arange(1, 2.5, 0.5)
one_ten=torch.arange(start=1, end=1000,step=77)
one_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [24]:
ten_zeros=torch.zeros_like(input=one_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# tensor datatypes
# Note are one of the three big issues you get into with pytorch and deep learning
# 1.Tensors not right datatype 2.Tensor not right shape 3.Tensor not on the right device

# Precision in computing https://en.wikipedia.org/wiki/Precision_(computer_science)

In [25]:
#float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,#if this dtype is 16 and running with 32 will get error
                             device=None, #None,cuda,cpu
                             requires_grad=False)#whether or not to track gradient with tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
#Manipulating Tensors
#creating tensor and adding it
tensor=torch.tensor([1,2,3,4])
tensor+10

tensor([11, 12, 13, 14])

In [30]:
#multiply tensor by 10
tensor*10

tensor([10, 20, 30, 40])

In [31]:
tensor

tensor([1, 2, 3, 4])

In [32]:
#subtract 10
tensor -10

tensor([-9, -8, -7, -6])

In [33]:
#torch Multiplication
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30, 40])

In [34]:
tensor

tensor([1, 2, 3, 4])

In [35]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3, 4]) * tensor([1, 2, 3, 4])
Equals: tensor([ 1,  4,  9, 16])


In [36]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [37]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 15.6 ms
Wall time: 263 μs


tensor(14)

In [38]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 213 μs


tensor(14)

In [39]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [40]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [41]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [42]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [43]:
%%time
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])
CPU times: total: 15.6 ms
Wall time: 11.5 ms


In [44]:
tensor @ tensor


tensor(14)

In [45]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [46]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [47]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [48]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [49]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()
y = torch.squeeze(x)
y.size()
y = torch.squeeze(x, 0)
y.size()
y = torch.squeeze(x, 1)
y.size()
y = torch.squeeze(x, (1, 2, 3))

In [3]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [4]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
#indexing selecting data from tensors
# Indexing with pytorch similar to numpy
#https://www.learnpytorch.io/00_pytorch_fundamentals/#indexing-selecting-data-from-tensors

In [32]:
# Common reshape examples claude
x = torch.arange(1, 10)  # [1,2,3,4,5,6,7,8,9] → shape: [9]

x.reshape(3, 3)      # 3×3 matrix       → shape: [3,3]
x.reshape(1, 9)      # 1 row, 9 columns → shape: [1,9]
x.reshape(9, 1)      # 9 rows, 1 column → shape: [9,1]
x.reshape(1, 3, 3)   # 1 block of 3×3  → shape: [1,3,3]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [33]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [6]:
#lets index on new tensor 
# Get all values of 0th dimension and the 0 index of 1st dimension
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
# lets index middle bracket
x[0][0]

tensor([1, 2, 3])

In [10]:
x[0][0][0]

tensor(1)

In [19]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]
x[0, 1, 1]

tensor(5)

In [28]:
#index on x to return 9
#x[1] #not working 
x[0][2][2]
#index to return 3,6,9

tensor(9)

In [ ]:
# # # PyTorch tensors & NumPy
# # # Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.
# # PyTorch tensors & NumPy
# # Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

# # The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

# # torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
# # torch.Tensor.numpy() - PyTorch tensor -> NumPy array.
# # Let's try them out.
# https://www.learnpytorch.io/00_pytorch_fundamentals/#pytorch-tensors-numpy

In [26]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [24]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.3944, 0.0205, 0.7476, 0.9864],
        [0.1494, 0.3530, 0.8013, 0.0154],
        [0.4678, 0.8879, 0.1938, 0.8606]])

Tensor B:
tensor([[0.6045, 0.8217, 0.3885, 0.0329],
        [0.8530, 0.5527, 0.7531, 0.3028],
        [0.9487, 0.8045, 0.1605, 0.9682]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [27]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:

# Running tensors on GPUs (and making faster computations)
# Deep learning algorithms require a lot of numerical operations.

# And by default these operations are often done on a CPU (computer processing unit).

# However, there's another common piece of hardware called a GPU (graphics processing unit), which is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs.

# Your computer might have one.

# If so, you should look to use it whenever you can to train neural networks because chances are it'll speed up the training time dramatically.

# There are a few ways to first get access to a GPU and secondly get PyTorch to use the GPU.

# Note: When I reference "GPU" throughout this course, I'm referencing a Nvidia GPU with CUDA enabled (CUDA is a computing platform and API that helps allow GPUs be used for general purpose computing & not just graphics) unless otherwise specified.

In [31]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [32]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [33]:
# Count number of devices
torch.cuda.device_count()

1

In [34]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [ ]:
# # https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises
# Resources:

# Exercise template notebook for 00.
# Example solutions notebook for 00 (try the exercises before looking at this).
# Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.
# Create a random tensor with shape (7, 7).
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
# Set the random seed to 0 and do exercises 2 & 3 over again.
# Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
# Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
# Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
# Find the maximum and minimum values of the output of 7.
# Find the maximum and minimum index values of the output of 7.
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.